import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "antd/dist/reset.css";
import "./globals.css";
import { ConfigProvider, theme } from "antd";
import esES from "antd/locale/es_ES";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body>
        <ConfigProvider
          locale={esES}
          theme={{
            algorithm: theme.defaultAlgorithm,
            token: {
              colorPrimary: "#0f766e", // teal médico
              colorInfo: "#0f766e",
              borderRadius: 8,
              fontSize: 14,
            },
            components: {
              Layout: { bodyBg: "#f6fffb" },
              Card: { headerBg: "#f0fdf4" },
              Tag: { defaultBg: "#ecfeff" },
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
